version: '3'
services:
  microWeb:
    image: jparedeshub/microweb:latest
    ports:
      - "8181:80"
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu2
    depends_on:
      - usuarios
      - productos
      - ordenes

  usuarios:
    image: jparedeshub/usuarios:latest
    ports:
      - "3001:3001"
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu1
    depends_on:
      - db_usuarios

  db_usuarios:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=usuarios_db
    volumes:
      - ./usuarios/db:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu1

  productos:
    image: jparedeshub/productos:latest
    ports:
      - "3002:3002"
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu1
    depends_on:
      - db_productos

  db_productos:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=productos_db
    volumes:
      - ./productos/db:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu1

  ordenes:
    image: jparedeshub/ordenes:latest
    ports:
      - "3003:3003"
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu1
    depends_on:
      - usuarios
      - productos
      - db_ordenes

  db_ordenes:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=ordenes_db
    volumes:
      - ./ordenes/db:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu1
